BLUETOOTH_PAGE_INDEX = 0
INSTRUMENT_PAGE_INDEX = 1

SELECTED_INSTRUMENT_STYLE = "border-radius: 20px;\nbackground-color: rgb(182, 182, 182);"
UNSELECTED_INSTRUMENT_STYLE = "border-radius: 20px;\nbackground-color: rgb(255, 255, 255);"

SELECTED_MENU_SIGN_DEFAULT_X_LOCATION = 30
SELECTED_MENU_SIGN_DEFAULT_Y_LOCATION = 85
VERTICAL_DISTANCE_BETWEEN_MENUS = 70

ANIMATION_SPEED = 650